apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"cache.example.com/v1alpha1","kind":"Broker","metadata":{"name":"example-broker"},"spec":{"size":3}}]'
    capabilities: Basic Install
  name: rocketmq-operator.v0.5.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Broker
      name: brokers.cache.example.com
      version: v1alpha1
  description: Placeholder description
  displayName: RocketMQ Operator
  install:
    spec:
      deployments:
      - name: rocketmq-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: rocketmq-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: rocketmq-operator
            spec:
              containers:
              - command:
                - rocketmq-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: rocketmq-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: rocketmq-operator
                resources: {}
              serviceAccountName: rocketmq-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - rocketmq-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - cache.example.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: rocketmq-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - broker
  - app
  maintainers:
  - email: corp@example.com
    name: Some Corp
  maturity: alpha
  provider:
    name: Example
    url: www.example.com
  version: 0.5.0
